services:
  postgres:
    image: postgres:18
    container_name: mono-db-container
    environment:
      POSTGRES_DB: mono_db
      POSTGRES_USER: mono_user
      POSTGRES_PASSWORD: mono_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
